import 'package:chat_with_aks/models/event_model.dart';

final List<EventModel> dummyEvents = [
  EventModel(
    id: 'evt1',
    title: 'AI & Robotics Workshop',
    date: 'Oct 12, 2024',
    time: '10:00 AM',
    location: 'UoM IT Fac.',
    host: 'AI Club',
    hostId: 'u1',
    hostName: 'Ahmed Hassan',
    hostAvatar: 'A',
    description:
        'Join us for an exciting workshop on AI and Robotics! Learn the fundamentals of artificial intelligence and robotics programming. This workshop is perfect for beginners and intermediate learners.\n\nWe will cover:\n• Introduction to AI concepts\n• Robotics basics and programming\n• Hands-on projects\n• Q&A session\n\nBring your laptops! Refreshments will be provided.',
    category: 'Workshop',
    attendeeCount: 12,
    attendees: ['u1', 'u2', 'u3', 'u4', 'u5'],
    imageUrl: '',
  ),
  EventModel(
    id: 'evt2',
    title: 'Medical Career Seminar',
    date: 'Nov 05, 2024',
    time: '2:00 PM',
    location: 'UoC Hall',
    host: 'Med Students',
    hostId: 'u2',
    hostName: 'Dr. Priya Sharma',
    hostAvatar: 'P',
    description:
        'Explore career opportunities in the medical field! This seminar brings together healthcare professionals, academics, and students to discuss various career paths in medicine.\n\nTopics:\n• Career paths in medicine\n• Medical education options\n• Internship & residency programs\n• Industry insights\n• Networking opportunities\n\nPerfect for pre-med and medical students!',
    category: 'Seminar',
    attendeeCount: 28,
    attendees: ['u2', 'u3', 'u4', 'u5', 'u6', 'u7', 'u8'],
    imageUrl: '',
  ),
  EventModel(
    id: 'evt3',
    title: 'Web Development Bootcamp',
    date: 'Oct 20, 2024',
    time: '3:30 PM',
    location: 'Tech Hub, Colombo',
    host: 'Code Masters',
    hostId: 'u3',
    hostName: 'Kasun Perera',
    hostAvatar: 'K',
    description:
        'Master modern web development in this intensive bootcamp! Learn React, Node.js, and database design in a hands-on environment.\n\nCurriculum:\n• Frontend: HTML, CSS, JavaScript, React\n• Backend: Node.js, Express\n• Databases: MongoDB, SQL\n• Deployment & DevOps\n\nLevel: Beginner to Intermediate\nDuration: 8 weeks\nFee: LKR 25,000',
    category: 'Bootcamp',
    attendeeCount: 45,
    attendees: ['u3', 'u4', 'u5'],
    imageUrl: '',
  ),
  EventModel(
    id: 'evt4',
    title: 'Career Fair 2024',
    date: 'Nov 15, 2024',
    time: '9:00 AM',
    location: 'University Main Grounds',
    host: 'Career Services',
    hostId: 'u4',
    hostName: 'Sarah Johnson',
    hostAvatar: 'S',
    description:
        'Annual Career Fair bringing together top employers and talented students! Meet recruiters from leading companies and explore job opportunities.\n\nParticipating Companies:\n• TechCorp Solutions\n• Finance & Co\n• Marketing Pros\n• HR Ventures\n• And many more!\n\nBring your resumes and dress professionally. Free career counseling throughout the day!',
    category: 'Fair',
    attendeeCount: 150,
    attendees: ['u4', 'u5', 'u6'],
    imageUrl: '',
  ),
];
